services:
  orders-app:
#    image: orders-app
    build:
      context: .
    ports:
      - "8080:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ordersdb
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - app-network

  mysql:
    image: mysql:9.2.0
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=test
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=ordersdb
    volumes:
      - /data:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/mysql
    networks:
      - app-network

#  postgres-db:
#    image: postgres:13
#    environment:
#      POSTGRES_DB: ordersdb
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: password
#    ports:
#      - "5432:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#    networks:
#      - app-network


volumes:
  pgdata:
networks:
  app-network: