server:
  port: 8083

spring:
  application:
    name: order
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME:root}
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://host.docker.internal:3307/microservicesTp1Orders}?createDatabaseIfNotExist=true
    password: ${SPRING_DATASOURCE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
  boot:
    admin:
      client:
        url : http://localhost:8088
  cloud:
    config:
      uri: http://localhost:8888
      enabled: true
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true


management:
  endpoints:
    web:
      exposure:
        include: "*"