server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: order
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME:root}
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/microservicesTp1Orders}?createDatabaseIfNotExist=true
    password: ${SPRING_DATASOURCE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
  boot:
    admin:
      client:
        url : ${SPRING_ADMIN_CLIENT_URL:http://localhost:8088}
  cloud:
    config:
      uri: ${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
      enabled: true
  config:
    import: ${SPRING_CLOUD_CONFIG_IMPORT:optional:configserver:http://localhost:8888}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true


management:
  endpoints:
    web:
      exposure:
        include: "*"