server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: product
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME:root}
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/microservicesTp1Products}?createDatabaseIfNotExist=true
    password: ${SPRING_DATASOURCE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
  boot:
      admin:
        client:
          url: http://localhost:8088
  cloud:
    config:
      uri: http://localhost:8888
      enabled: true
  config:
    import: optional:configserver:http://localhost:8888
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true


management:
  endpoints:
    web:
      exposure:
        include: "*"