spring:
  application:
    name: service-discovery
server:
  port: ${SERVER_PORT:8761}
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

