server:
  port: 8888


spring:
  application:
    name: confServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ZARAYACH/microservicesTp/configFiles
          clone-on-start: true
          default-label: master
  security:
    user:
      password: admin
      name: admin